import Carousel from 'react-bootstrap/Carousel';

function Finance() {
  return (
    <div>
      <div className="article">
        <br />
        <h3>Finance</h3>
        <br />
        
        <Carousel slide={false} >
      <Carousel.Item>
        <img src="/Finance1.jpg" className="article_banner" />
      </Carousel.Item>
      <Carousel.Item>
      <img src="/Finance2.jpg" className="article_banner" />
      </Carousel.Item>
      <Carousel.Item>
      <img src="/Finance3.jpg" className="article_banner" />
      </Carousel.Item>
      <Carousel.Item>
      <img src="/Finance4c.jpg" className="article_banner" />
      </Carousel.Item>
    </Carousel>
        
        <br />
        <br />
        <b>Summary</b>
        <ul>
          <li>Learn to budget</li>
          <li>Educate yourself</li>
          <li>Control credit</li>
          <li>Start an emergency fond</li>
        </ul>
        <br />
        <div className="intro">
          It’s tricky to jump from a safe financial environment that was out of
          your care into daily worries about …well, basically everything you
          need, from food to divertissement.
          <br />
          <br />
          Financial chaos in your personal life can create frustration and
          extend beyond the relationships with the goods you can buy/ or not. To
          avoid those, you need to understand some simple ideas that will help
          you avoid the panic in this domain and let you concentrate on the rest
          of aspects of your life.
        </div>
        <br /> <br />
        <h5>Learn to budget</h5>
        <div className="subarticle">
          <img src="/Finance1.jpg" className="article_photo" />
          Never let your expenses exceed your income sound like an easy thing to
          do, but can proof to be one of the hardest to achieve if you don’t pay
          attention to it.
          <br />
          In order to stay on top of it, make a list with:
          <br />
          - All your fix monthly expenses: rent/ bank rate, power bill, phone/
          net bill…so on.
          <br />
          - Monthly sum for necessities: food, cleaning supplies, self-hygiene
          fonds. <br />
          - Recurring expenses generated by your habits: weekly/ daily take out,
          monthly subscription…
          <br />
          <br />
          Sum it all up and compare it with your income, if it’s less- all good,
          if it’s bigger, soon you’ll be in a bucket of frustration and a pile
          of wrong decision. To avoid the second scenario, analyze for each
          category:
          <br />
          <br />
          - If you can not decrease the amount paid for 1st 2 categories: maybe
          you can get a better offer for utilities from other supplier, or maybe
          you can find a cheaper place from where to buy necessities, without
          renouncing to quality levels. Also, especially for food, take a look
          if you consume everything you buy- if you end up throwing away every
          week a part of it means that you can adjust immediately quantities.
          <br />- If all recurring expenses are really needed: it’s possible
          that you’ll find subscription to channels that you don’t follow since
          months. And the one that can seem hardest of all, if you were fooled
          to believe in the marketing trick that you should spend in order to
          enjoy, cut / replace some. You have 2 perspectives here: to be a numb
          slave of some habits or to have the liberty to enjoy life.
        </div>
        <br /> <br />
        <br />
        <h5>Educate yourself</h5>
        <div className="subarticle">
          <br />
          <img src="/Finance2.jpg" className="article_photo" />
          You learned to walk, wash yourself, speak, drive a car, how to do a
          job that is assuring your income. In the same way, you should learn
          how to take care of your money and what are/ can be the consequences
          if you don’t.
          <br />
          Start with basic knowledge for personal finances. Research for blogs,
          vlogs and any other type of information that is out there (we are
          living in a ocean of information). Try to don’t pay for it, at
          begging- the idea is to take of money, not to spend. Before you start
          following advices, make brief research of the people providing those
          advices: try to see what their life/ proven experience/ others are
          saying about them.
          <br />
          If you master the basic knowledge about finance, you’ll be harder to
          be the subject of a fraud or to be influenced by people that I
          spending like is no tomorrow and when tomorrow comes complain that
          bread is to expensive.
          <br />
          And keep this in mind: if something seems for free, usually you are
          the product.
        </div>
        <br /> <br />
        <br />
        <h5>Control credit</h5>
        <div className="subarticle">
          <img src="/Finance3.jpg" className="article_photo" />
          Exercise patience and self-control when you want to spend. Don’t start
          your life with big loans, because it will proof to be a burden that
          you don’t need at beginning of your life. Better to save money for
          what you need, this way you’ll not accumulate interest on top of your
          spending. Think that, if seems hard to do it like this, when you can
          establish your own pace, it will be even more unpleasant when the bank
          will control both the pace and the amount. Don’t forget that interest
          varies and our recent economic demonstrated large climbs of it with
          dire consequences.
          <br />
          Also, this will be the best training experience for future spendings
          (like a house) when credit will be needed-. If you’re used to control
          your money, you’ll own your life, otherwise, your creditors will.
        </div>
        <br /> <br />
        <br />
        <h5>Start an emergency fond</h5>
        <div className="subarticle">
          <br />
          <img src="/Finance4.jpg" className="article_photo" />
          Enjoy every day, prepare for a great future, but don’t be an ignorant
          please: don’t ignore that bad things can happen. Nobody wishes that,
          but you can get ill, your car can break, you can lose your job. Any of
          those events is unpleasant and challenging by itself so you shouldn’t
          add on top also the worry of money. That’s why is better if you have a
          stash of money put away, to help you navigate through bad times.{" "}
          <br />
          The recommendations vary about the boundaries of the emergency fond,
          but majority are talking about a reserve able to cover all your
          spendings between 3 and 6 months. Start building it easy: like to put
          every month when you take your salary 5% away. You can increase latter
          on, if seems manageable for you and, you’ll discover that when your
          fond is build, you’ll be able to use this formed habit for next steps
          in your financial-wise path: savings and investments.
          <br />
          <br />
          If you follow these tips, you be set for financial security, that is
          part of foundation for a free life.
        </div>
      </div>
    </div>
  );
}

export default Finance;
